
############################
# STEP 1 build executable binary
############################
FROM golang:alpine AS builder
RUN apk update && apk add --no-cache git
RUN apk add bash
RUN apk add build-base

# Force the go compiler to use modules
ENV GO111MODULE=on

# Set the Current Working Directory inside the container
WORKDIR $GOPATH/src/app/backend

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . .

# Download all the dependencies
RUN go mod download
RUN go mod tidy
RUN go build -o application
RUN cp application /go/bin

#RUN go clean -testcache && go test -tags=integration ./...

EXPOSE 8080

# Run the executable
#CMD  ["./application"]
