
version: "3.9"

services:
  tests:
    build:
      context: ./
      dockerfile: Dockerfile-integration-tests
    links:
      - sftp:sftp
    depends_on:
      - sftp
    networks:
      - testnet
    restart: on-failure

  sftp:
    image: atmoz/sftp
    ports:
      - "2224:22"
    command: user:pass:1001
    networks:
      - testnet

networks:
  testnet:
    name: testnet
    driver: bridge
