name: Peer Review

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache Go modules
      uses: actions/cache@preview
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Get dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod tidy

    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...

    - name: coverage
      run: |
            go test ./... -coverprofile=c.out
            cat c.out >> coverage.txt

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
        fail_ci_if_error: true
