name: Peer Review

on:
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy the testing services
      run: docker-compose -f docker-compose-integration-tests.yml up -d

    - name: Running the integration tests
      run: docker-compose -f docker-compose-integration-tests.yml run tests go test -tags=integration ./...

    - name: stop the testing services
      run: docker-compose -f docker-compose-integration-tests.yml stop
